# some more ls aliases
alias ll='ls -alF'
alias la='ls -A'
alias l='ls -CF'

# powerlevel10k 的主体
source ~/.zsh/powerlevel10k/powerlevel10k.zsh-theme

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh

# autosuggestions 同一行的灰色提示,记住以前输入的命令
source ~/.zsh/zsh-autosuggestions/zsh-autosuggestions.zsh

# syntax-highlighting
source ~/.zsh/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh

# completions
export fpath=(~/.zsh/zsh-completions/src $fpath)


export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

# 执行系统
source ~/.profile

SOURCE_DIR="${HOME}/.xu/source/"
# 遍历执行source
FILES=$(find "$SOURCE_DIR" -name '*.sh' | sort)
for FILE in $FILES; do
    source $FILE
done

source ~/working/soft/z/z.sh
